version: '3.8'

services:
  scanservjs:
    image: scanservjs:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - SANED_NET_HOSTS=192.168.1.1
      - OCR_LANG=rus+eng
