name: scanservjs CI

on:
  push:
    tags:
      - scanservjs-v*

  pull_request:
    paths:
      - 'scanservjs/**'
      - '.github/workflows/scanservjs-ci.yml'
      
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            VERSION=$(curl -s https://api.github.com/repos/sbs20/scanservjs/releases/latest | grep '"name": "v' | cut -d '"' -f 4 | sed -e 's/^v//')
            docker build . --file Dockerfile --build-arg APP_VERSION=$VERSION
          fi
        working-directory: scanservjs

  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

        
      - name: Define version
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          [[ "${{ github.event.inputs.version }}" ]] && VERSION=${{ github.event.inputs.version }}
          
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^scanservjs-v//')

          echo VERSION=$VERSION
          echo "::set-output name=VERSION::$VERSION"
        id: set-version
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./scanservjs
          build-args: APP_VERSION=${{ steps.set-version.outputs.VERSION }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/scanservjs:${{ steps.set-version.outputs.VERSION }}
            
